<?php
namespace app\modules\personaloffice\models;
use app\modules\backend\models\Constants;

class Clients extends \app\modules\personaloffice\models\base\Clients
{
    function beforeSave($insert)
    {
        $this->user->group_id = Constants::getConstantByName('defaultUsersGroup');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}